<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Group_8_Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Group_8_Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group_8_Analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Group_8_Analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Group_8_Analysis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Group_8_Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Group_8_Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Group_8_Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Group_8_Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group_8_Analysis_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Group_8_Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Group_8_Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Group_8_Analysis_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>
details.code-fold summary {
  color: darkgreen !important;
  font-weight: 600;
}
details.code-fold summary:hover {
  color: darkgreen !important;
}

.quarto-title-block .subtitle {
  color: dimgray !important;
  font-weight: 500 !important;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link active" data-scroll-target="#sec-intro"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-rq" id="toc-sec-rq" class="nav-link" data-scroll-target="#sec-rq"><span class="header-section-number">2</span> Research Question</a></li>
  <li><a href="#sec-dataset" id="toc-sec-dataset" class="nav-link" data-scroll-target="#sec-dataset"><span class="header-section-number">3</span> The Dataset</a>
  <ul class="collapse">
  <li><a href="#sec-insp-data" id="toc-sec-insp-data" class="nav-link" data-scroll-target="#sec-insp-data"><span class="header-section-number">3.1</span> Inspect the dataset</a></li>
  <li><a href="#sec-var-desc" id="toc-sec-var-desc" class="nav-link" data-scroll-target="#sec-var-desc"><span class="header-section-number">3.2</span> Variable descriptions</a></li>
  </ul></li>
  <li><a href="#sec-eda" id="toc-sec-eda" class="nav-link" data-scroll-target="#sec-eda"><span class="header-section-number">4</span> Exploratory Analysis</a>
  <ul class="collapse">
  <li><a href="#sec-year" id="toc-sec-year" class="nav-link" data-scroll-target="#sec-year"><span class="header-section-number">4.1</span> Release Year and High IMDB Ratings</a></li>
  <li><a href="#sec-length" id="toc-sec-length" class="nav-link" data-scroll-target="#sec-length"><span class="header-section-number">4.2</span> Film Length and IMDB Ratings</a></li>
  <li><a href="#sec-budget" id="toc-sec-budget" class="nav-link" data-scroll-target="#sec-budget"><span class="header-section-number">4.3</span> Production budget and IMDB Ratings</a></li>
  <li><a href="#sec-votes" id="toc-sec-votes" class="nav-link" data-scroll-target="#sec-votes"><span class="header-section-number">4.4</span> Votes and High IMDB Ratings</a></li>
  <li><a href="#sec-genre" id="toc-sec-genre" class="nav-link" data-scroll-target="#sec-genre"><span class="header-section-number">4.5</span> Film Genre and High IMDB Ratings</a></li>
  </ul></li>
  <li><a href="#sec-model" id="toc-sec-model" class="nav-link" data-scroll-target="#sec-model"><span class="header-section-number">5</span> Model Fitting</a>
  <ul class="collapse">
  <li><a href="#sec-data-pre" id="toc-sec-data-pre" class="nav-link" data-scroll-target="#sec-data-pre"><span class="header-section-number">5.1</span> Data Preprocessing</a></li>
  <li><a href="#sec-full-model" id="toc-sec-full-model" class="nav-link" data-scroll-target="#sec-full-model"><span class="header-section-number">5.2</span> Fitting Full Model</a></li>
  <li><a href="#sec-reduced-model" id="toc-sec-reduced-model" class="nav-link" data-scroll-target="#sec-reduced-model"><span class="header-section-number">5.3</span> Fitting Reduced Model</a></li>
  <li><a href="#sec-model-comp" id="toc-sec-model-comp" class="nav-link" data-scroll-target="#sec-model-comp"><span class="header-section-number">5.4</span> Model comparison</a>
  <ul class="collapse">
  <li><a href="#sec-model-coef" id="toc-sec-model-coef" class="nav-link" data-scroll-target="#sec-model-coef"><span class="header-section-number">5.4.1</span> Coefficient Comparison Table</a></li>
  <li><a href="#sec-model-statis" id="toc-sec-model-statis" class="nav-link" data-scroll-target="#sec-model-statis"><span class="header-section-number">5.4.2</span> Model Fitting Statistics Table</a></li>
  </ul></li>
  <li><a href="#sec-model-slec" id="toc-sec-model-slec" class="nav-link" data-scroll-target="#sec-model-slec"><span class="header-section-number">5.5</span> Final Model Selection</a></li>
  <li><a href="#sec-odds" id="toc-sec-odds" class="nav-link" data-scroll-target="#sec-odds"><span class="header-section-number">5.6</span> Odds Ratios of the Final Model</a></li>
  <li><a href="#sec-predict" id="toc-sec-predict" class="nav-link" data-scroll-target="#sec-predict"><span class="header-section-number">5.7</span> Predicted Probabilities</a></li>
  </ul></li>
  <li><a href="#sec-limit" id="toc-sec-limit" class="nav-link" data-scroll-target="#sec-limit"><span class="header-section-number">6</span> Model Limitation</a></li>
  <li><a href="#sec-future" id="toc-sec-future" class="nav-link" data-scroll-target="#sec-future"><span class="header-section-number">7</span> Future Work</a></li>
  <li><a href="#sec-conclusion" id="toc-sec-conclusion" class="nav-link" data-scroll-target="#sec-conclusion"><span class="header-section-number">8</span> Conclusion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Group_8_Analysis</h1>
<p class="subtitle lead">Which properties of films influence whether they are rated by IMDB as greater than 7 or not?</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages for data analysis and visualisation</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)   <span class="co"># Data visualisation</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># Data manipulation and general workflow tools</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)        <span class="co"># Table formatting</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)     <span class="co"># Convert model outputs into tidy data frames</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)     <span class="co"># Create formatted tables in the report</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)     <span class="co"># Data manipulation functions</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)    <span class="co"># Enhanced data frame tools</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="sec-intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>This study investigates which film characteristics influence whether a film receives an IMDB rating greater than 7. IMDB ratings are widely used as an indicator of audience perception and overall film quality, as they are based on a large number of user evaluations.</p>
<p>Understanding which characteristics are associated with higher ratings may provide insights into what factors contribute to the perceived success of a film. In particular, features such as release year, film length, number of votes and genre may influence how audiences evaluate movies.</p>
<p>To investigate this question, a binary response variable is created to indicate whether a film has an IMDB rating above 7. A logistic regression model within the Generalised Linear Model framework is used to examine how film characteristics influence the probability of receiving a high rating.</p>
</section>
<section id="sec-rq" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Research Question</h1>
<p>The aim of this analysis is to examine which film characteristics are associated with whether a film receives an IMDB rating greater than 7 or not.</p>
<p>To address this question, a binary response variable is considered, taking the value 1 if a film has an IMDB rating above 7 and 0 otherwise. The analysis focuses on whether release year, film length, production budget, number of votes, and genre are related to the probability of receiving a high rating.</p>
<p>Given that the response variable is binary, the analysis employs logistic regression as part of the Generalised Linear Model framework.</p>
</section>
<section id="sec-dataset" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> The Dataset</h1>
<p>The dataset used in this analysis comes from the IMDB film database, which provides a large collection of information about films and their characteristics. The data analysed here represent a subset of this database containing key variables relevant to film popularity and ratings.</p>
<section id="sec-insp-data" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-insp-data"><span class="header-section-number">3.1</span> Inspect the dataset</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the movie dataset from the CSV file</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>movies <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"dataset08.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>After loading the dataset, the first few observations are displayed to provide an initial overview of the data.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first six rows to inspect the structure of the dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(movies)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  film_id year length budget votes       genre rating
1    5993 1943     65   15.5    42      Action    7.6
2   37190 1961     87   12.3     6       Drama    6.0
3   43646 1987     79   16.4   161      Action    7.5
4   28476 1976     NA   12.2     5 Documentary    8.0
5   23975 1982     88   12.5    97      Action    3.5
6   50170 1936     NA    7.0   146       Drama    4.4</code></pre>
</div>
</div>
<p>The structure of the dataset is examined to identify the variables and their data types.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the structure of the dataset</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This shows variable types and basic information about each column</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(movies)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Based on the structure output, the dataset contains 2,847 observations and seven variables. Specifically, film_id, year, length, and votes are stored as integer variables, while budget and rating are numeric variables. The genre variable is recorded as a character variable representing film categories. The structure output also suggests that some variables, such as length, contain missing values (NA).</p>
<p>To further explore the distribution of the variables in the dataset, summary statistics are computed.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce basic summary statistics for all variables</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(movies)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select numerical variables for descriptive statistics</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>numeric_vars <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(film_id, year, length, budget, votes, rating)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute key descriptive statistics for each variable</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>numeric_stats <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(numeric_vars, <span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">min</span>(.,            <span class="at">na.rm =</span> <span class="cn">TRUE</span>))), <span class="co"># Minimum</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(numeric_vars, <span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">quantile</span>(., <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))), <span class="co"># 1st quartile</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(numeric_vars, <span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">median</span>(.,         <span class="at">na.rm =</span> <span class="cn">TRUE</span>))), <span class="co"># Median</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(numeric_vars, <span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">mean</span>(.,           <span class="at">na.rm =</span> <span class="cn">TRUE</span>))), <span class="co"># Mean</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(numeric_vars, <span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">quantile</span>(., <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))), <span class="co"># 3rd quartile</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(numeric_vars, <span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">max</span>(.,            <span class="at">na.rm =</span> <span class="cn">TRUE</span>))), <span class="co"># Maximum</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(numeric_vars, <span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.))))                     <span class="co"># Number of missing values</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Transpose the table to present variables as rows</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>numeric_stats <span class="ot">&lt;-</span> numeric_stats <span class="sc">%&gt;%</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">"Min"</span>, <span class="st">"1st Qu"</span>, <span class="st">"Median"</span>, <span class="st">"Mean"</span>, <span class="st">"3rd Qu"</span>, <span class="st">"Max"</span>, <span class="st">"Missing"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">"Variable"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>Variable, <span class="sc">~</span><span class="fu">round</span>(<span class="fu">as.numeric</span>(.), <span class="dv">2</span>))) <span class="co"># Round results for readability</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the formatted table</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(numeric_stats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-numvars" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-numvars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary statistics for numerical variables
</figcaption>
<div aria-describedby="tbl-numvars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">1st Qu</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">3rd Qu</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">film_id</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: right;">14159.5</td>
<td style="text-align: right;">29447.0</td>
<td style="text-align: right;">29180.86</td>
<td style="text-align: right;">43982.0</td>
<td style="text-align: right;">58748.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">1898.0</td>
<td style="text-align: right;">1957.0</td>
<td style="text-align: right;">1982.0</td>
<td style="text-align: right;">1975.75</td>
<td style="text-align: right;">1997.0</td>
<td style="text-align: right;">2005.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">73.0</td>
<td style="text-align: right;">90.0</td>
<td style="text-align: right;">82.22</td>
<td style="text-align: right;">101.0</td>
<td style="text-align: right;">480.0</td>
<td style="text-align: right;">131</td>
</tr>
<tr class="even">
<td style="text-align: left;">budget</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">11.9</td>
<td style="text-align: right;">11.85</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">22.3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">votes</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">29.0</td>
<td style="text-align: right;">657.03</td>
<td style="text-align: right;">114.0</td>
<td style="text-align: right;">149494.0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">rating</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">5.34</td>
<td style="text-align: right;">7.7</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-numvars" class="quarto-xref">Table&nbsp;1</a> presents the summary statistics for the numerical variables included in the analysis.</p>
<p>As shown in <a href="#tbl-numvars" class="quarto-xref">Table&nbsp;1</a>, the release year of the films spans from 1898 to 2005, suggesting that the dataset covers a long historical period. Film length ranges from 1 to 480 minutes. The production budget ranges between 2.5 and 22.3, while the number of votes shows particularly large variation, with a maximum value of 149,494. In contrast, film ratings appear to be relatively concentrated, with values ranging from 0.8 to 9.2. It is also noteworthy that the variable <em>length</em> contains 131 missing observations, whereas the remaining numerical variables do not exhibit missing values.</p>
<p>In addition to the numerical variables, the distribution of film genres is also examined.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of films in each genre</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>genre_summary <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(genre, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the genre frequency table</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(genre_summary, <span class="at">caption =</span> <span class="st">"Number of films by genre"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-genre" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-genre-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Distribution of films across genres
</figcaption>
<div aria-describedby="tbl-genre-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<caption>Number of films by genre</caption>
<thead>
<tr class="header">
<th style="text-align: left;">genre</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Action</td>
<td style="text-align: right;">872</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">797</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">684</td>
</tr>
<tr class="even">
<td style="text-align: left;">Animation</td>
<td style="text-align: right;">178</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Documentary</td>
<td style="text-align: right;">154</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short</td>
<td style="text-align: right;">131</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Romance</td>
<td style="text-align: right;">31</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-genre" class="quarto-xref">Table&nbsp;2</a> reports the number of films in each genre. Action, Drama, and Comedy account for the largest number of observations, whereas genres such as Animation, Documentary, Short, and Romance appear less frequently. This suggests that the dataset is dominated by a few major genres.</p>
</section>
<section id="sec-var-desc" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-var-desc"><span class="header-section-number">3.2</span> Variable descriptions</h2>
<p>In this dataset, each film is represented by several variables describing its main characteristics. <a href="#tbl-variable" class="quarto-xref">Table&nbsp;3</a> shows the main variables used, including their data types and brief descriptions.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame that summarises the main variables in the dataset</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>var_desc <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">"film_id"</span>, <span class="st">"year"</span>, <span class="st">"length"</span>, <span class="st">"budget"</span>, <span class="st">"votes"</span>, <span class="st">"genre"</span>, <span class="st">"rating"</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Type =</span> <span class="fu">c</span>(<span class="st">"Integer"</span>, <span class="st">"Integer"</span>, <span class="st">"Numeric"</span>, <span class="st">"Numeric"</span>, <span class="st">"Integer"</span>, <span class="st">"Character"</span>, <span class="st">"Numeric"</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Description =</span> <span class="fu">c</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"The unique identifier for the film"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Year of release of the film in cinemas"</span>,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Duration (in minutes)"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Budget for the films production (in $1000000s)"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Number of positive votes received by viewers"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Genre of the film"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IMDB rating from 0-10"</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the variable description table</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(var_desc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-variable" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Description of variables in the dataset
</figcaption>
<div aria-describedby="tbl-variable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">film_id</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">The unique identifier for the film</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">Year of release of the film in cinemas</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Duration (in minutes)</td>
</tr>
<tr class="even">
<td style="text-align: left;">budget</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">Budget for the films production (in $1000000s)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">votes</td>
<td style="text-align: left;">Integer</td>
<td style="text-align: left;">Number of positive votes received by viewers</td>
</tr>
<tr class="even">
<td style="text-align: left;">genre</td>
<td style="text-align: left;">Character</td>
<td style="text-align: left;">Genre of the film</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rating</td>
<td style="text-align: left;">Numeric</td>
<td style="text-align: left;">IMDB rating from 0-10</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-variable" class="quarto-xref">Table&nbsp;3</a> shows the variables included in the dataset.</p>
<p>The dataset contains both numerical and categorical variables describing different aspects of each film. These variables will later be used as predictors in the statistical model.</p>
</section>
</section>
<section id="sec-eda" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Exploratory Analysis</h1>
<p>Before fitting the GLM, exploratory analysis was carried out to examine the relationships between the response variable and the candidate predictors. This helps to identify broad patterns in the data and provides preliminary support for variable selection in the modelling stage.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a binary response variable for the logistic regression</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1 = IMDB rating above 7</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 0 = IMDB rating 7 or below</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>movies<span class="sc">$</span>high_rating <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(movies<span class="sc">$</span>rating <span class="sc">&gt;</span> <span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="sec-year" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-year"><span class="header-section-number">4.1</span> Release Year and High IMDB Ratings</h2>
<p>Release year may influence how films are rated. To explore this, films were grouped by release decade and the proportion of highly rated films (IMDB rating &gt; 7) was calculated for each group.</p>
<p>Very early decades contained only a small number of films, so films released before 1910 were excluded from this plot to provide a more stable comparison across release periods.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dataset summarising high ratings by release decade</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>movies_year <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">1910</span>) <span class="sc">%&gt;%</span>                     <span class="co"># Remove very early films with few observations</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">decade =</span> <span class="fu">floor</span>(year<span class="sc">/</span><span class="dv">10</span>)<span class="sc">*</span><span class="dv">10</span>) <span class="sc">%&gt;%</span>       <span class="co"># Convert year into decade groups</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(decade) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">proportion_high =</span> <span class="fu">mean</span>(high_rating, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Proportion of high ratings</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>()                                         <span class="co"># Number of films in each decade</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the proportion of high-rated films across decades</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(movies_year, <span class="fu">aes</span>(<span class="at">x =</span> decade, <span class="at">y =</span> proportion_high)) <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> <span class="st">"mediumpurple"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">colour =</span> <span class="st">"gold2"</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(movies<span class="sc">$</span>high_rating),     <span class="co"># Overall proportion reference line</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"coral"</span>,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Decade"</span>,</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of Films with Rating &gt; 7"</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-explo-year" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-explo-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_8_Analysis_files/figure-html/fig-explo-year-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-explo-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Proportion of Highly Rated Films by Release Decade
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-explo-year" class="quarto-xref">Figure&nbsp;1</a> shows the proportion of highly rated films across release decades. The dashed horizontal line represents the overall proportion of films with ratings above 7 in the dataset.</p>
<p>The proportion of highly rated films appears to vary across decades. Earlier decades tend to show somewhat higher proportions, while films released between the 1950s and 1980s appear to have relatively lower proportions. However, some early decades contain relatively few films, so these proportions should be interpreted with caution.</p>
</section>
<section id="sec-length" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-length"><span class="header-section-number">4.2</span> Film Length and IMDB Ratings</h2>
<p>Film length may influence audience perception of a movie. To explore this relationship, film length is treated as a continuous variable and the relationship between film length and the probability of receiving a high rating is visualised using a logistic smoothing curve.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove observations with missing film length values</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>movies_length <span class="ot">&lt;-</span> <span class="fu">subset</span>(movies, <span class="sc">!</span><span class="fu">is.na</span>(length))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot relationship between film length and probability of high rating</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(movies_length, <span class="fu">aes</span>(<span class="at">x =</span> length, <span class="at">y =</span> high_rating)) <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">colour =</span> <span class="st">"pink"</span>) <span class="sc">+</span> <span class="co"># Scatter points with jitter</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>,                                <span class="co"># Logistic regression smoothing</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"navy"</span>) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Film Length (minutes)"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Probability of High Rating"</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-explo-length" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-explo-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_8_Analysis_files/figure-html/fig-explo-length-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-explo-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Relationship Between Film Length and the Probability of High IMDB Ratings
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-explo-length" class="quarto-xref">Figure&nbsp;2</a> shows the relationship between film length and the probability of receiving a high IMDB rating.</p>
<p>The probability of receiving a rating above 7 appears to be higher for shorter films and gradually decreases as film length increases. This suggests that film length may be associated with high ratings, although the pattern may partly reflect differences in genre composition across films of different lengths.</p>
</section>
<section id="sec-budget" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-budget"><span class="header-section-number">4.3</span> Production budget and IMDB Ratings</h2>
<p>Film budget may also influence how audiences perceive a movie. To explore this possibility, the distribution of film budgets and their relationship with IMDB ratings were examined.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot relationship between film budget and probability of high rating</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(movies,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> budget,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> high_rating)) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span>                  <span class="co"># Scatter points</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"glm"</span>,                                          <span class="co"># Logistic smoothing curve</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family=</span><span class="st">"binomial"</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"red"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-explo-budget" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-explo-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_8_Analysis_files/figure-html/fig-explo-budget-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-explo-budget-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Relationship between film budget and the probability of receiving a high IMDB rating
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-explo-budget" class="quarto-xref">Figure&nbsp;3</a> shows the relationship between film production budget and the probability of receiving a high IMDB rating. Each point represents an individual film, and the red curve corresponds to the fitted logistic regression line.</p>
<p>The fitted curve shows a gradual upward trend, suggesting that films with larger budgets may be somewhat more likely to receive high ratings. This suggests that budget may be positively associated with the likelihood of a film receiving a high rating.</p>
</section>
<section id="sec-votes" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-votes"><span class="header-section-number">4.4</span> Votes and High IMDB Ratings</h2>
<p>The number of votes may reflect a film’s popularity or level of audience engagement. Since the distribution of votes is highly skewed, with some films receiving far more votes than others, direct comparisons using raw vote counts are difficult. Therefore, films were divided into five groups based on vote quantiles so that each group contains approximately the same number of observations. This grouping allows the proportion of highly rated films to be compared across different levels of audience engagement while reducing the influence of extreme vote counts.</p>
<p>The approximate vote ranges for the five groups are:<br>
Very Low: 5-10 votes<br>
Low: 10-20 votes<br>
Medium: 20-47 votes<br>
High: 47-174 votes<br>
Very High: above 174 votes.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Divide vote counts into five groups using quantiles</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>vote_breaks <span class="ot">&lt;-</span> <span class="fu">quantile</span>(movies<span class="sc">$</span>votes, <span class="at">probs =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="fl">0.2</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a categorical variable representing vote groups</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>movies<span class="sc">$</span>vote_group <span class="ot">&lt;-</span> <span class="fu">cut</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  movies<span class="sc">$</span>votes,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> vote_breaks,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">include.lowest =</span> <span class="cn">TRUE</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Very Low"</span>, <span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>, <span class="st">"Very High"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate proportion of high ratings in each vote group</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>prop_table <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(high_rating <span class="sc">~</span> vote_group,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> movies,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>                        <span class="at">FUN =</span> mean)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot proportion of high ratings by vote group</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(prop_table, <span class="fu">aes</span>(<span class="at">x =</span> vote_group, <span class="at">y =</span> high_rating)) <span class="sc">+</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>) <span class="sc">+</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(movies<span class="sc">$</span>high_rating), <span class="co"># Overall proportion</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"red"</span>,</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>             <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Vote Groups"</span>,</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of Films with Rating &gt; 7"</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-explo-votes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-explo-votes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_8_Analysis_files/figure-html/fig-explo-votes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-explo-votes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Proportion of High IMDB Ratings Across Vote Groups
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-explo-votes" class="quarto-xref">Figure&nbsp;4</a> shows the proportion of highly rated films across vote groups. The dashed horizontal line represents the overall proportion of films with ratings above 7 in the dataset.</p>
<p>The proportion of highly rated films appears to vary across vote groups, with lower-vote groups showing slightly higher proportions than higher-vote groups. Although the pattern is not especially strong, it suggests that the relationship between vote count and high ratings may not be straightforward.</p>
</section>
<section id="sec-genre" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sec-genre"><span class="header-section-number">4.5</span> Film Genre and High IMDB Ratings</h2>
<p>Film genre may influence how movies are perceived by audiences. Different genres may attract different audiences and may vary in storytelling style, which could affect IMDB ratings.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate proportion of highly rated films for each genre</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>genre_prop <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">proportion_high =</span> <span class="fu">mean</span>(high_rating, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">count =</span> <span class="fu">n</span>()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot high rating proportion by genre</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(genre_prop,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(genre, proportion_high),</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> proportion_high)) <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"seagreen"</span>) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(movies<span class="sc">$</span>high_rating, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Overall proportion</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"darkred"</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Genre"</span>,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion of Films with Rating &gt; 7"</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-explo-genre" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-explo-genre-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_8_Analysis_files/figure-html/fig-explo-genre-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-explo-genre-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Proportion of Highly Rated Films by Genre
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-explo-genre" class="quarto-xref">Figure&nbsp;5</a> shows substantial variation in the proportion of highly rated films across genres. Some genres have much higher proportions of films with ratings above 7 than others.</p>
<p>This suggests that genre may be an important predictor of high ratings. However, some genres contain relatively few observations, so the corresponding proportions may be less stable and should be interpreted cautiously.</p>
</section>
</section>
<section id="sec-model" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Model Fitting</h1>
<section id="sec-data-pre" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-data-pre"><span class="header-section-number">5.1</span> Data Preprocessing</h2>
<p>Before fitting the logistic regression models, a modelling dataset was created by selecting the variables required for the analysis and removing observations with missing values. In this analysis, the response variable is high_rating, while the candidate predictors are release year, film length, production budget, number of votes, and genre.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create modelling dataset by selecting relevant variables</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>movies_model <span class="ot">&lt;-</span> movies <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(high_rating, year, length, budget, votes, genre) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()   <span class="co"># Remove rows with any missing values</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert genre into a categorical variable</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>movies_model<span class="sc">$</span>genre <span class="ot">&lt;-</span> <span class="fu">factor</span>(movies_model<span class="sc">$</span>genre)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The raw distribution of film genres was previously presented in <a href="#tbl-genre" class="quarto-xref">Table&nbsp;2</a>, and the proportion of highly rated films across genres was illustrated in <a href="#fig-explo-genre" class="quarto-xref">Figure&nbsp;5</a>. However, the logistic regression model uses the complete dataset after removing rows with missing values. Therefore, the reference category for genre should be chosen based on the final modelling sample rather than the raw dataset.</p>
<p>To assess which genre is most suitable as the reference category, the distribution of the binary outcome variable (high_rating) across genres is examined in the modelling dataset.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarise the outcome distribution for each genre in the modelling dataset</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>genre_outcome_model <span class="ot">&lt;-</span> movies_model <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),  <span class="co"># n = total number of films in the genre  </span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">high_rating_0 =</span> <span class="fu">sum</span>(high_rating <span class="sc">==</span> <span class="dv">0</span>),  <span class="co"># high_rating_0 = number of films with rating &lt;= 7</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">high_rating_1 =</span> <span class="fu">sum</span>(high_rating <span class="sc">==</span> <span class="dv">1</span>),  <span class="co"># high_rating_1 = number of films with rating &gt; 7</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">prop_high =</span> <span class="fu">mean</span>(high_rating)  <span class="co"># prop_high = proportion of films with rating &gt; 7</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n))</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary table</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(genre_outcome_model, <span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-genre-model" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-genre-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Distribution of high ratings across genres in the modelling dataset
</figcaption>
<div aria-describedby="tbl-genre-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">genre</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">high_rating_0</th>
<th style="text-align: right;">high_rating_1</th>
<th style="text-align: right;">prop_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Action</td>
<td style="text-align: right;">826</td>
<td style="text-align: right;">709</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">0.142</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drama</td>
<td style="text-align: right;">761</td>
<td style="text-align: right;">719</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">0.055</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comedy</td>
<td style="text-align: right;">647</td>
<td style="text-align: right;">276</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">0.573</td>
</tr>
<tr class="even">
<td style="text-align: left;">Animation</td>
<td style="text-align: right;">174</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">0.678</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Documentary</td>
<td style="text-align: right;">149</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">138</td>
<td style="text-align: right;">0.926</td>
</tr>
<tr class="even">
<td style="text-align: left;">Short</td>
<td style="text-align: right;">131</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">0.985</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Romance</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-genre-model" class="quarto-xref">Table&nbsp;4</a> shows that the genre categories differ significantly in both sample size and outcome distribution. Action has the largest number of observations in the modelling dataset, which makes it a stable category for comparison. In addition, Action contains both low-rated and high-rated films, rather than being concentrated almost entirely in one outcome group.</p>
<p>Some genres exhibit much more extreme outcome distributions. For example, Romance contains no films with ratings above 7, while Short and Documentary are heavily concentrated in the high-rating group. Among the remaining genres, Drama is strongly skewed towards low-rated films, whereas Comedy and Animation are relatively more concentrated in higher ratings. Compared with these categories, Action represents a more moderate and less extreme distribution.</p>
<p>To visualise these differences more clearly, <a href="#fig-genre-model" class="quarto-xref">Figure&nbsp;6</a> shows the proportion of low-rated and high-rated films within each genre.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a proportional bar chart to show the composition of high_rating within each genre</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(movies_model, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(genre, <span class="sc">-</span><span class="fu">table</span>(genre)[genre]), <span class="at">fill =</span> <span class="fu">factor</span>(high_rating))) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span>   <span class="co"># Show proportions instead of counts</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Genre"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proportion"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"High Rating"</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_discrete</span>(</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0 = Rating &lt;= 7"</span>, <span class="st">"1 = Rating &gt; 7"</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-genre-model" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-genre-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_8_Analysis_files/figure-html/fig-genre-model-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-genre-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Proportion of low-rated and high-rated films within each genre in the modelling dataset
</figcaption>
</figure>
</div>
</div>
</div>
<p>For these reasons, Action was selected as the reference category for genre. This choice is supported by three aspects: it remains the largest genre in the modelling dataset, it provides a relatively stable baseline, and it allows for meaningful comparisons across genres.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set Action as the reference category for genre</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>movies_model<span class="sc">$</span>genre <span class="ot">&lt;-</span> <span class="fu">relevel</span>(movies_model<span class="sc">$</span>genre, <span class="at">ref =</span> <span class="st">"Action"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>After preprocessing, the modelling dataset is ready for logistic regression analysis, with genre coded as a categorical variable and Action defined as the baseline category for comparison.</p>
</section>
<section id="sec-full-model" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-full-model"><span class="header-section-number">5.2</span> Fitting Full Model</h2>
<p>After data preprocessing, a full logistic regression model was fitted to investigate how film characteristics are associated with the probability of receiving a high IMDB rating.</p>
<p>In this analysis, the response variable is binary. Let <span class="math inline">\(Y_i\)</span> be the binary response for film <span class="math inline">\(i\)</span>, where <span class="math inline">\(Y_i = 1\)</span> if the film has an IMDB rating above 7 and <span class="math inline">\(Y_i = 0\)</span> otherwise. Let <span class="math inline">\(p_i = P(Y_i = 1)\)</span> denote the probability that film <span class="math inline">\(i\)</span> receives a high IMDB rating. Since the response variable is binary, logistic regression with a logit link is used.</p>
<p>The full model can be written as</p>
<p><span class="math display">\[
\text{logit}(p_i)=\log\left(\frac{p_i}{1-p_i}\right)
= \beta_0 + \beta_1 \text{year}_i + \beta_2 \text{length}_i + \beta_3 \text{budget}_i + \beta_4 \text{votes}_i + \text{genre effect}_i
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the intercept term for the reference genre;</li>
<li><span class="math inline">\(\beta_1\)</span> is the coefficient for release year;</li>
<li><span class="math inline">\(\beta_2\)</span> is the coefficient for film length;</li>
<li><span class="math inline">\(\beta_3\)</span> is the coefficient for production budget;</li>
<li><span class="math inline">\(\beta_4\)</span> is the coefficient for the number of votes;</li>
<li><span class="math inline">\(\text{genre effect}_i\)</span> represents the set of genre indicator terms, with each genre coefficient interpreted relative to the reference genre;</li>
<li><span class="math inline">\(p_i\)</span> is the probability that film <span class="math inline">\(i\)</span> receives a high IMDB rating;</li>
<li><span class="math inline">\(\text{logit}(p_i)=\log\left(\frac{p_i}{1-p_i}\right)\)</span> is the logit transformation, that is, the logarithm of the odds.</li>
</ul>
<p>The logit transformation is appropriate because the response variable is binary. Rather than modelling the probability directly, logistic regression models the log-odds of receiving a high rating as a linear combination of the predictors. A positive regression coefficient indicates that the corresponding predictor increases the log-odds, and hence the probability, of a film receiving a high rating, while a negative coefficient indicates the opposite.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the full logistic regression model</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>model_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  high_rating <span class="sc">~</span> year <span class="sc">+</span> length <span class="sc">+</span> budget <span class="sc">+</span> votes <span class="sc">+</span> genre,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> movies_model,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model results in a formatted table</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_full) <span class="sc">%&gt;%</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"Estimate"</span>, <span class="st">"Std Error"</span>, <span class="st">"z value"</span>, <span class="st">"p value"</span>),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Logistic regression results (full model)"</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-full-model" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-full-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Logistic regression results (full model)
</figcaption>
<div aria-describedby="tbl-full-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-23.616</td>
<td style="text-align: right;">5.789</td>
<td style="text-align: right;">-4.079</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">3.429</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-16.003</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">budget</td>
<td style="text-align: right;">0.510</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">16.935</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">votes</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.508</td>
<td style="text-align: right;">0.612</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreAnimation</td>
<td style="text-align: right;">-0.089</td>
<td style="text-align: right;">0.321</td>
<td style="text-align: right;">-0.277</td>
<td style="text-align: right;">0.782</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreComedy</td>
<td style="text-align: right;">3.109</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">17.351</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreDocumentary</td>
<td style="text-align: right;">5.608</td>
<td style="text-align: right;">0.443</td>
<td style="text-align: right;">12.661</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreDrama</td>
<td style="text-align: right;">-1.557</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">-6.506</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreRomance</td>
<td style="text-align: right;">-14.604</td>
<td style="text-align: right;">391.708</td>
<td style="text-align: right;">-0.037</td>
<td style="text-align: right;">0.970</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreShort</td>
<td style="text-align: right;">4.002</td>
<td style="text-align: right;">0.797</td>
<td style="text-align: right;">5.021</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The coefficient estimates for the full model are presented in <a href="#tbl-full-model" class="quarto-xref">Table&nbsp;5</a>. Statistical significance is assessed at the 5% level throughout the analysis, so predictors with p-values below 0.05 are regarded as statistically significant. The results show that votes is not statistically significant, suggesting that it does not provide strong evidence of an independent contribution once the other variables are included in the model.</p>
<p>Compared with this, year, length, budget, and several genre categories show statistically significant associations with the odds of receiving a high rating. Overall, the full model suggests that more recent films and films with larger production budgets tend to have higher odds of receiving an IMDB rating above 7, while longer films tend to have lower odds. In addition, the estimated genre effects indicate that the probability of receiving a high rating differs across film genres. These findings provide the basis for considering a simpler model that excludes the non-significant predictor votes.</p>
</section>
<section id="sec-reduced-model" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-reduced-model"><span class="header-section-number">5.3</span> Fitting Reduced Model</h2>
<p>Since votes was not statistically significant in the full model, a reduced logistic regression model was fitted after removing this variable. The purpose of removing this variable is to examine whether the model can be improved after excluding votes.</p>
<p>The reduced model can be written as</p>
<p><span class="math display">\[
\text{logit}(p_i)=\log\left(\frac{p_i}{1-p_i}\right)
= \beta_0 + \beta_1 \text{year}_i + \beta_2 \text{length}_i + \beta_3 \text{budget}_i + \text{genre effect}_i
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the intercept term for the reference genre;</li>
<li><span class="math inline">\(\beta_1\)</span> is the coefficient for release year;</li>
<li><span class="math inline">\(\beta_2\)</span> is the coefficient for film length;</li>
<li><span class="math inline">\(\beta_3\)</span> is the coefficient for production budget;</li>
<li><span class="math inline">\(\text{genre effect}_i\)</span> represents the set of genre indicator terms, with each genre coefficient interpreted relative to the reference genre;</li>
<li><span class="math inline">\(p_i\)</span> is the probability that film <span class="math inline">\(i\)</span> receives a high IMDB rating;</li>
<li><span class="math inline">\(\text{logit}(p_i)=\log\left(\frac{p_i}{1-p_i}\right)\)</span> is the logit transformation, that is, the logarithm of the odds.</li>
</ul>
<p>Thus, the reduced model retains the key explanatory variables from the full model while excluding the non-significant predictor votes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit reduced model excluding votes</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>model_reduced <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  high_rating <span class="sc">~</span> year <span class="sc">+</span> length <span class="sc">+</span> budget <span class="sc">+</span> genre,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> movies_model,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> binomial</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display reduced model results</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_reduced) <span class="sc">%&gt;%</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">"Estimate"</span>, <span class="st">"Std Error"</span>, <span class="st">"z value"</span>, <span class="st">"p value"</span>),</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Logistic regression results (reduced model)"</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-reduced-model" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reduced-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Logistic regression results (reduced model)
</figcaption>
<div aria-describedby="tbl-reduced-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-23.864</td>
<td style="text-align: right;">5.767</td>
<td style="text-align: right;">-4.138</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">3.483</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-16.077</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">budget</td>
<td style="text-align: right;">0.510</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">16.933</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreAnimation</td>
<td style="text-align: right;">-0.079</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">-0.246</td>
<td style="text-align: right;">0.806</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreComedy</td>
<td style="text-align: right;">3.111</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">17.362</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreDocumentary</td>
<td style="text-align: right;">5.605</td>
<td style="text-align: right;">0.442</td>
<td style="text-align: right;">12.673</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreDrama</td>
<td style="text-align: right;">-1.557</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">-6.509</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreRomance</td>
<td style="text-align: right;">-14.608</td>
<td style="text-align: right;">391.829</td>
<td style="text-align: right;">-0.037</td>
<td style="text-align: right;">0.970</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreShort</td>
<td style="text-align: right;">4.006</td>
<td style="text-align: right;">0.797</td>
<td style="text-align: right;">5.028</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The coefficient estimates for the reduced model are presented in <a href="#tbl-reduced-model" class="quarto-xref">Table&nbsp;6</a>. The results show that, after removing votes, the main predictors in the model remain statistically significant at the 5% level. In particular, year and budget still have positive estimated effects, while length still has a negative estimated effect.</p>
<p>The genre coefficients also continue to show differences between genres in their association with high IMDB ratings. Compared with the full model, the overall pattern of results remains stable after excluding votes. This suggests that votes contributes little to the model, and that the reduced model is still able to capture the main relationships between film characteristics and the probability of receiving a high rating.</p>
</section>
<section id="sec-model-comp" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-model-comp"><span class="header-section-number">5.4</span> Model comparison</h2>
<section id="sec-model-coef" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="sec-model-coef"><span class="header-section-number">5.4.1</span> Coefficient Comparison Table</h3>
<p>To compare the full and reduced models, the estimated coefficients are presented side by side in <a href="#tbl-model-comp" class="quarto-xref">Table&nbsp;7</a>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficients from full model</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>full_coef <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model_full) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Full_Model =</span> estimate)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficients from reduced model</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>reduced_coef <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model_reduced) <span class="sc">%&gt;%</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Reduced_Model =</span> estimate)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine results into a comparison table</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>comparison <span class="ot">&lt;-</span> full_coef <span class="sc">%&gt;%</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(reduced_coef, <span class="at">by =</span> <span class="st">"term"</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Display comparison table</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  comparison,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Predictor"</span>, <span class="st">"Full Model"</span>, <span class="st">"Reduced Model"</span>),</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Comparison of coefficients between full and reduced models"</span></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-model-comp" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-comp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Comparison of coefficients between full and reduced models
</figcaption>
<div aria-describedby="tbl-model-comp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">Full Model</th>
<th style="text-align: right;">Reduced Model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-23.616</td>
<td style="text-align: right;">-23.864</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length</td>
<td style="text-align: right;">-0.057</td>
<td style="text-align: right;">-0.057</td>
</tr>
<tr class="even">
<td style="text-align: left;">budget</td>
<td style="text-align: right;">0.510</td>
<td style="text-align: right;">0.510</td>
</tr>
<tr class="odd">
<td style="text-align: left;">votes</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreAnimation</td>
<td style="text-align: right;">-0.089</td>
<td style="text-align: right;">-0.079</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreComedy</td>
<td style="text-align: right;">3.109</td>
<td style="text-align: right;">3.111</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreDocumentary</td>
<td style="text-align: right;">5.608</td>
<td style="text-align: right;">5.605</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreDrama</td>
<td style="text-align: right;">-1.557</td>
<td style="text-align: right;">-1.557</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreRomance</td>
<td style="text-align: right;">-14.604</td>
<td style="text-align: right;">-14.608</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreShort</td>
<td style="text-align: right;">4.002</td>
<td style="text-align: right;">4.006</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As shown in <a href="#tbl-model-comp" class="quarto-xref">Table&nbsp;7</a>, removing the non-significant variable votes leads to only negligible changes in the estimated coefficients of the remaining predictors. In particular, the coefficients for release year, film length, production budget, and the genre categories remain very similar in magnitude and direction across the two models. This indicates that excluding votes has little impact on the estimated relationships between the other predictors and the probability of receiving a high IMDB rating.</p>
</section>
<section id="sec-model-statis" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="sec-model-statis"><span class="header-section-number">5.4.2</span> Model Fitting Statistics Table</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table of model fit statistics</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># AIC is used to compare model fit while accounting for model complexity</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual deviance and residual degrees of freedom are also reported</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>model_fit <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Full model"</span>, <span class="st">"Reduced model"</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">AIC =</span> <span class="fu">c</span>(<span class="fu">AIC</span>(model_full), <span class="fu">AIC</span>(model_reduced)),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Residual_Deviance =</span> <span class="fu">c</span>(<span class="fu">deviance</span>(model_full), <span class="fu">deviance</span>(model_reduced)),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">DF =</span> <span class="fu">c</span>(<span class="fu">df.residual</span>(model_full), <span class="fu">df.residual</span>(model_reduced))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the model fit statistics table</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  model_fit,</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Model fit statistics for the full and reduced models"</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-model-statis" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model-statis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Model fit statistics for the full and reduced models
</figcaption>
<div aria-describedby="tbl-model-statis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">Residual_Deviance</th>
<th style="text-align: right;">DF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Full model</td>
<td style="text-align: right;">1478.365</td>
<td style="text-align: right;">1456.365</td>
<td style="text-align: right;">2705</td>
</tr>
<tr class="even">
<td style="text-align: left;">Reduced model</td>
<td style="text-align: right;">1476.593</td>
<td style="text-align: right;">1456.593</td>
<td style="text-align: right;">2706</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The model fitting statistics for the full and reduced models are presented in <a href="#tbl-model-statis" class="quarto-xref">Table&nbsp;8</a>. The reduced model has a slightly lower AIC than the full model, which indicates a better balance between model fit and model complexity. Although the residual deviance of the reduced model is marginally higher than that of the full model, the difference is negligible. This indicates that removing the variable votes leads to almost no loss of explanatory power while producing a simpler model.</p>
</section>
</section>
<section id="sec-model-slec" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-model-slec"><span class="header-section-number">5.5</span> Final Model Selection</h2>
<p>In the full model, the coefficient for the number of votes was not statistically significant. After removing this variable, the reduced model produced a slightly lower AIC and almost the same residual deviance as the full model. In addition, the comparison of coefficients between the two models showed that the estimated effects of the remaining predictors changed very little after excluding votes. Therefore, the reduced model was selected as the final model because it achieves a slight improvement in overall model performance while maintaining a very similar level of fit, and provides a more parsimonious representation of the data.</p>
<p>The final selected model is:</p>
<p><span class="math display">\[
\text{logit}(p_i)=\log\left(\frac{p_i}{1-p_i}\right)
= \beta_0 + \beta_1 \text{year}_i + \beta_2 \text{length}_i + \beta_3 \text{budget}_i + \text{genre effect}_i
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the intercept term for the reference genre;</li>
<li><span class="math inline">\(\beta_1\)</span> is the coefficient for release year;</li>
<li><span class="math inline">\(\beta_2\)</span> is the coefficient for film length;</li>
<li><span class="math inline">\(\beta_3\)</span> is the coefficient for production budget;</li>
<li><span class="math inline">\(\text{genre effect}_i\)</span> represents the set of genre indicator terms, with each genre coefficient interpreted relative to the reference genre;</li>
<li><span class="math inline">\(p_i\)</span> is the probability that film <span class="math inline">\(i\)</span> receives a high IMDB rating;</li>
<li><span class="math inline">\(\text{logit}(p_i)=\log\left(\frac{p_i}{1-p_i}\right)\)</span> is the logit transformation, that is, the logarithm of the odds.</li>
</ul>
</section>
<section id="sec-odds" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-odds"><span class="header-section-number">5.6</span> Odds Ratios of the Final Model</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert logistic regression coefficients to odds ratios</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>or_reduced <span class="ot">&lt;-</span> <span class="fu">tidy</span>(model_reduced, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">OR =</span> <span class="fu">exp</span>(estimate),       <span class="co"># Odds ratio</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">CI_low =</span> <span class="fu">exp</span>(conf.low),   <span class="co"># Lower confidence interval</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">CI_high =</span> <span class="fu">exp</span>(conf.high)  <span class="co"># Upper confidence interval</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, OR, std.error, statistic, p.value, CI_low, CI_high)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Display odds ratio table</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  or_reduced,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Predictor"</span>, <span class="st">"OR"</span>, <span class="st">"SE"</span>, <span class="st">"z"</span>, <span class="st">"p"</span>, <span class="st">"CI low"</span>, <span class="st">"CI high"</span>),</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Odds ratios for the reduced logistic regression model"</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="tbl-or-reduced" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-or-reduced-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Odds ratios for the reduced logistic regression model
</figcaption>
<div aria-describedby="tbl-or-reduced-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">OR</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">z</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">CI low</th>
<th style="text-align: right;">CI high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">5.767</td>
<td style="text-align: right;">-4.138</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">year</td>
<td style="text-align: right;">1.010</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">3.483</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.005</td>
<td style="text-align: right;">1.016</td>
</tr>
<tr class="odd">
<td style="text-align: left;">length</td>
<td style="text-align: right;">0.945</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">-16.077</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.938</td>
<td style="text-align: right;">0.951</td>
</tr>
<tr class="even">
<td style="text-align: left;">budget</td>
<td style="text-align: right;">1.665</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">16.933</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.572</td>
<td style="text-align: right;">1.769</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreAnimation</td>
<td style="text-align: right;">0.924</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">-0.246</td>
<td style="text-align: right;">0.806</td>
<td style="text-align: right;">0.491</td>
<td style="text-align: right;">1.725</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreComedy</td>
<td style="text-align: right;">22.439</td>
<td style="text-align: right;">0.179</td>
<td style="text-align: right;">17.362</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">15.905</td>
<td style="text-align: right;">32.119</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreDocumentary</td>
<td style="text-align: right;">271.756</td>
<td style="text-align: right;">0.442</td>
<td style="text-align: right;">12.673</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">119.805</td>
<td style="text-align: right;">683.371</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreDrama</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">-6.509</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.130</td>
<td style="text-align: right;">0.333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">genreRomance</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">391.829</td>
<td style="text-align: right;">-0.037</td>
<td style="text-align: right;">0.970</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">207.390</td>
</tr>
<tr class="even">
<td style="text-align: left;">genreShort</td>
<td style="text-align: right;">54.903</td>
<td style="text-align: right;">0.797</td>
<td style="text-align: right;">5.028</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">14.173</td>
<td style="text-align: right;">370.971</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-or-reduced" class="quarto-xref">Table&nbsp;9</a> presents the odds ratios from the final logistic regression model. The odds ratios are obtained by exponentiating the estimated coefficients and provide an interpretable measure of how each predictor affects the odds that a film receives an IMDB rating above 7, holding the other variables constant.</p>
</section>
<section id="sec-predict" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-predict"><span class="header-section-number">5.7</span> Predicted Probabilities</h2>
<p>To further illustrate the final logistic regression model, predicted probabilities were calculated using the reduced model. Film length was allowed to vary across its observed range, while release year and production budget were held constant at their mean values.</p>
<p>Predicted probabilities were generated for several selected genres in order to visualise how the probability of receiving an IMDB rating above 7 changes with film length and genre.</p>
<p>For classification purposes, a default cutoff value of 0.5 was also specified in the prediction code. This means that a film would be classified as predicted high rating if its predicted probability is greater than 0.5, and as not high rating otherwise.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new dataset for prediction</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">length =</span> <span class="fu">seq</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">min</span>(movies_model<span class="sc">$</span>length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">max</span>(movies_model<span class="sc">$</span>length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">length.out =</span> <span class="dv">100</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="fu">mean</span>(movies_model<span class="sc">$</span>year, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),   <span class="co"># Fix year at mean value</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">budget =</span> <span class="fu">mean</span>(movies_model<span class="sc">$</span>budget, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Fix budget at mean value</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">genre =</span> <span class="fu">c</span>(<span class="st">"Action"</span>, <span class="st">"Comedy"</span>, <span class="st">"Documentary"</span>, <span class="st">"Drama"</span>, <span class="st">"Short"</span>) <span class="co"># Selected genres</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate predicted probabilities from the reduced model</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>newdata<span class="sc">$</span>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  model_reduced,</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">newdata =</span> newdata,</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"response"</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Set classification rule</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>cutoff <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>newdata<span class="sc">$</span>pred_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(newdata<span class="sc">$</span>pred_prob <span class="sc">&gt;</span> cutoff, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot predicted probabilities</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdata, <span class="fu">aes</span>(<span class="at">x =</span> length, <span class="at">y =</span> pred_prob, <span class="at">colour =</span> genre)) <span class="sc">+</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Film Length (minutes)"</span>,</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Probability"</span>,</span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">colour =</span> <span class="st">"Genre"</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-pred-prob" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pred-prob-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Group_8_Analysis_files/figure-html/fig-pred-prob-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pred-prob-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Predicted Probability of High IMDB Rating by Film Length and Genre
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-pred-prob" class="quarto-xref">Figure&nbsp;7</a> shows the predicted probability that a film receives an IMDB rating above 7 across different film lengths for several selected genres.</p>
<p>The predicted probabilities decrease as film length increases, indicating that longer films are generally less likely to receive ratings above 7 according to the fitted model. This pattern is consistent with the negative coefficient of film length observed in the logistic regression results.</p>
<p>Differences between genres can be clearly seen. Documentary films consistently have the highest probability of receiving a rating above 7 across most film lengths, with Short films also showing relatively high probabilities. Comedy films show moderate probabilities, followed by Action films. Meanwhile, Drama films have the lowest probability of receiving a rating above 7 across the range of film lengths considered.</p>
<p>Overall, the figure illustrates how the final logistic regression model combines the effects of film length and genre to predict the probability that a film achieves an IMDB rating above 7, while holding the other predictors constant.</p>
</section>
</section>
<section id="sec-limit" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Model Limitation</h1>
<p>This analysis has several limitations that should be taken into account when interpreting the results.</p>
<p>First, the dataset contains only a limited number of film characteristics, including release year, film length, production budget, number of votes, and genre. Other potentially important factors, such as director, cast, country of production, awards, marketing exposure, or distribution platform, are not included. As a result, the fitted model may omit variables that also influence whether a film receives an IMDB rating above 7.</p>
<p>Second, missing values in film length were handled by removing incomplete observations before model fitting. Although this produces a simple and consistent modelling dataset, it reduces the sample size and may introduce bias if the missing values are not completely random.</p>
<p>Third, some genres contain relatively small numbers of films compared with the larger categories. This may lead to less stable coefficient estimates for those smaller groups, so the corresponding genre effects should be interpreted with caution.</p>
<p>Finally, the analysis is based on a binary transformation of the original IMDB rating. While this makes logistic regression suitable and allows a clear distinction between high-rated and non-high-rated films, it also simplifies the original rating scale and may lose some information contained in the full range of ratings.</p>
</section>
<section id="sec-future" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Future Work</h1>
<p>There are several ways in which this analysis could be extended in future work.</p>
<p>First, more explanatory variables could be added to the model. Including information such as director, actors, awards, country of production, or distribution platform may provide a more complete understanding of the factors associated with high IMDB ratings.</p>
<p>Second, alternative approaches to handling missing data could be considered. Instead of removing incomplete observations, future analysis could explore imputation methods and compare whether the results remain consistent.</p>
<p>Third, the current analysis focuses on main effects only. Future work could investigate whether interaction effects are present. For example, the relationship between film length and rating may differ across genres, or the effect of budget may vary across release periods.</p>
</section>
<section id="sec-conclusion" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Conclusion</h1>
<p>This analysis examined which film characteristics are associated with whether a film receives an IMDB rating greater than 7. To answer this question, a binary response variable was created to distinguish films with ratings above 7 from those with ratings of 7 or below, and logistic regression was used to model the probability of receiving a high rating.</p>
<p>A full model including release year, film length, production budget, number of votes, and genre was first fitted. Since the number of votes was not statistically significant, a reduced model excluding this variable was selected as the final model. The reduced model achieved a slightly lower AIC than the full model, while the estimated effects of the remaining predictors stayed broadly similar. This suggests that removing votes improved the model slightly.</p>
<p>Overall, the final model indicates that release year, film length, production budget, and genre are important predictors of whether a film receives an IMDB rating above 7. In particular, more recent films and films with larger production budgets tend to have higher odds of receiving a high rating, while longer films tend to have lower odds. Differences across genres were also evident, indicating that genre plays an important role in the probability of a film being highly rated.</p>
<p>In summary, these findings show that logistic regression provides a useful and interpretable framework for examining how film characteristics are associated with high IMDB ratings. Although the model does not capture every factor that may influence audience evaluation, it provides a clear statistical summary of the main relationships in this dataset.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>